# Generated by Django 4.1 on 2023-05-23 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Univ_Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=20, null=True)),
                ('major', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('position', models.CharField(blank=True, max_length=20, null=True)),
                ('task', models.CharField(blank=True, max_length=200, null=True)),
                ('contact', models.CharField(blank=True, default='042-280', max_length=20)),
                ('second_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('third_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unimaze_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=200)),
                ('title', models.CharField(default='', max_length=200)),
                ('text', models.TextField(default='tag를 입력하세요. 각 층에 해당하는 교수님, 업무, 교직원 등등, 모든 걸 다 작성해주세요.')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unimaze_map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=20)),
                ('building_num', models.IntegerField(default='', null=True)),
                ('floor', models.CharField(default='', max_length=100)),
                ('vectary_viewer_key', models.CharField(default='', max_length=50)),
                ('text', models.TextField(default='tag를 입력하세요. 각 층에 해당하는 교수님, 업무, 교직원 등등, 모든 걸 다 작성해주세요.')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
